### ISSUE TITLE
Note type posts throw Type Error: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by paulrobertlloyd** [twozeroone/post-type-discovery#3]
This package currently throws an error (shown below) if the provided mf2 object doesn’t include a `name` property, which is often the case for note type posts.

```
TypeError: Cannot read property '0' of undefined
    at getValue (/Users/paulrobertlloyd/Sites/indiekit/node_modules/post-type-discovery/index.js:12:15)
    at getType (/Users/paulrobertlloyd/Sites/indiekit/node_modules/post-type-discovery/index.js:74:14)
    at Object.module.exports [as createPost] (/Users/paulrobertlloyd/Sites/indiekit/app/lib/micropub/create-post.js:33:12)
    at getResult (/Users/paulrobertlloyd/Sites/indiekit/app/routes/micropub.js:88:23)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**Comment by paulrobertlloyd** [comment]
Updating the following on line 74 fixes this issue:

```diff
- var name = getValue( prop.name );
+ var name = prop.name ? getValue( prop.name ) : undefined; 
```

Happy to make a PR if you feel this is the right approach.

**Comment by prtksxna** [comment]
Thanks for reporting the issues @paulrobertlloyd 🙂The approach looks correct, I'd be happy to merge a PR.

**Comment by prtksxna** [comment]
Do you have an example of when this happens? I tried a note from your website and it seems to contain the name: https://glennjones.net/tools/microformats/?url=https%3A%2F%2Fpaulrobertlloyd.com%2Fnotes%2F1563227099&callback=&dateformat=auto
